package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2017-12-28T12:58:56.551-03:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceSoap {

    @WebMethod(operationName = "RemoveInternetExceptionWeb", action = "http://tempuri.org/RemoveInternetExceptionWeb")
    @RequestWrapper(localName = "RemoveInternetExceptionWeb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveInternetExceptionWeb")
    @ResponseWrapper(localName = "RemoveInternetExceptionWebResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveInternetExceptionWebResponse")
    public void removeInternetExceptionWeb();

    @WebMethod(operationName = "CRM_Mostrando_Contacto", action = "http://tempuri.org/CRM_Mostrando_Contacto")
    @RequestWrapper(localName = "CRM_Mostrando_Contacto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMMostrandoContacto")
    @ResponseWrapper(localName = "CRM_Mostrando_ContactoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMMostrandoContactoResponse")
    public void crmMostrandoContacto(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "IDCONTACTO", targetNamespace = "http://tempuri.org/")
        int idcontacto,
        @WebParam(name = "DATA", targetNamespace = "http://tempuri.org/")
        java.lang.String data
    );

    @WebMethod(operationName = "Iniciar_Grabacion", action = "http://tempuri.org/Iniciar_Grabacion")
    @RequestWrapper(localName = "Iniciar_Grabacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IniciarGrabacion")
    @ResponseWrapper(localName = "Iniciar_GrabacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IniciarGrabacionResponse")
    public void iniciarGrabacion(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Modificar_Dispositivo", action = "http://tempuri.org/Modificar_Dispositivo")
    @RequestWrapper(localName = "Modificar_Dispositivo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModificarDispositivo")
    @ResponseWrapper(localName = "Modificar_DispositivoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModificarDispositivoResponse")
    public void modificarDispositivo(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "DEVICE", targetNamespace = "http://tempuri.org/")
        java.lang.String device,
        @WebParam(name = "CLAVE", targetNamespace = "http://tempuri.org/")
        java.lang.String clave,
        @WebParam(name = "FECHA_EXPIRACION", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaEXPIRACION,
        @WebParam(name = "CONFIGURACION", targetNamespace = "http://tempuri.org/")
        java.lang.String configuracion,
        @WebParam(name = "ENABLED", targetNamespace = "http://tempuri.org/")
        boolean enabled,
        @WebParam(name = "CANALES_MAX", targetNamespace = "http://tempuri.org/")
        int canalesMAX,
        @WebParam(name = "TIPO_ASTERISK", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoASTERISK,
        @WebParam(name = "TIPO_NEOTEL", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoNEOTEL,
        @WebParam(name = "PROVEEDOR", targetNamespace = "http://tempuri.org/")
        java.lang.String proveedor,
        @WebParam(name = "DESCRIPCION", targetNamespace = "http://tempuri.org/")
        java.lang.String descripcion,
        @WebParam(name = "InternalCall", targetNamespace = "http://tempuri.org/")
        boolean internalCall
    );

    @WebMethod(operationName = "KickAll", action = "http://tempuri.org/KickAll")
    @RequestWrapper(localName = "KickAll", targetNamespace = "http://tempuri.org/", className = "org.tempuri.KickAll")
    @ResponseWrapper(localName = "KickAllResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.KickAllResponse")
    public void kickAll(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia
    );

    @WebMethod(operationName = "ExecuteTask17", action = "http://tempuri.org/ExecuteTask17")
    @RequestWrapper(localName = "ExecuteTask17", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask17")
    @ResponseWrapper(localName = "ExecuteTask17Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask17Response")
    @WebResult(name = "ExecuteTask17Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask17(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11,
        @WebParam(name = "param12", targetNamespace = "http://tempuri.org/")
        java.lang.String param12,
        @WebParam(name = "param13", targetNamespace = "http://tempuri.org/")
        java.lang.String param13,
        @WebParam(name = "param14", targetNamespace = "http://tempuri.org/")
        java.lang.String param14,
        @WebParam(name = "param15", targetNamespace = "http://tempuri.org/")
        java.lang.String param15,
        @WebParam(name = "param16", targetNamespace = "http://tempuri.org/")
        java.lang.String param16,
        @WebParam(name = "param17", targetNamespace = "http://tempuri.org/")
        java.lang.String param17
    );

    @WebMethod(operationName = "ExecuteTask18", action = "http://tempuri.org/ExecuteTask18")
    @RequestWrapper(localName = "ExecuteTask18", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask18")
    @ResponseWrapper(localName = "ExecuteTask18Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask18Response")
    @WebResult(name = "ExecuteTask18Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask18(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11,
        @WebParam(name = "param12", targetNamespace = "http://tempuri.org/")
        java.lang.String param12,
        @WebParam(name = "param13", targetNamespace = "http://tempuri.org/")
        java.lang.String param13,
        @WebParam(name = "param14", targetNamespace = "http://tempuri.org/")
        java.lang.String param14,
        @WebParam(name = "param15", targetNamespace = "http://tempuri.org/")
        java.lang.String param15,
        @WebParam(name = "param16", targetNamespace = "http://tempuri.org/")
        java.lang.String param16,
        @WebParam(name = "param17", targetNamespace = "http://tempuri.org/")
        java.lang.String param17,
        @WebParam(name = "param18", targetNamespace = "http://tempuri.org/")
        java.lang.String param18
    );

    @WebMethod(operationName = "ExecuteTask19", action = "http://tempuri.org/ExecuteTask19")
    @RequestWrapper(localName = "ExecuteTask19", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask19")
    @ResponseWrapper(localName = "ExecuteTask19Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask19Response")
    @WebResult(name = "ExecuteTask19Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask19(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11,
        @WebParam(name = "param12", targetNamespace = "http://tempuri.org/")
        java.lang.String param12,
        @WebParam(name = "param13", targetNamespace = "http://tempuri.org/")
        java.lang.String param13,
        @WebParam(name = "param14", targetNamespace = "http://tempuri.org/")
        java.lang.String param14,
        @WebParam(name = "param15", targetNamespace = "http://tempuri.org/")
        java.lang.String param15,
        @WebParam(name = "param16", targetNamespace = "http://tempuri.org/")
        java.lang.String param16,
        @WebParam(name = "param17", targetNamespace = "http://tempuri.org/")
        java.lang.String param17,
        @WebParam(name = "param18", targetNamespace = "http://tempuri.org/")
        java.lang.String param18,
        @WebParam(name = "param19", targetNamespace = "http://tempuri.org/")
        java.lang.String param19
    );

    @WebMethod(operationName = "BlindTransferCampaign", action = "http://tempuri.org/BlindTransferCampaign")
    @RequestWrapper(localName = "BlindTransferCampaign", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BlindTransferCampaign")
    @ResponseWrapper(localName = "BlindTransferCampaignResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BlindTransferCampaignResponse")
    public void blindTransferCampaign(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CAMPAÑA", targetNamespace = "http://tempuri.org/")
        int campaña
    );

    @WebMethod(operationName = "Login_Campaign", action = "http://tempuri.org/Login_Campaign")
    @RequestWrapper(localName = "Login_Campaign", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginCampaign")
    @ResponseWrapper(localName = "Login_CampaignResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginCampaignResponse")
    public void loginCampaign(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CAMPAÑA", targetNamespace = "http://tempuri.org/")
        int campaña
    );

    @WebMethod(operationName = "ExecuteTask20", action = "http://tempuri.org/ExecuteTask20")
    @RequestWrapper(localName = "ExecuteTask20", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask20")
    @ResponseWrapper(localName = "ExecuteTask20Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask20Response")
    @WebResult(name = "ExecuteTask20Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask20(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11,
        @WebParam(name = "param12", targetNamespace = "http://tempuri.org/")
        java.lang.String param12,
        @WebParam(name = "param13", targetNamespace = "http://tempuri.org/")
        java.lang.String param13,
        @WebParam(name = "param14", targetNamespace = "http://tempuri.org/")
        java.lang.String param14,
        @WebParam(name = "param15", targetNamespace = "http://tempuri.org/")
        java.lang.String param15,
        @WebParam(name = "param16", targetNamespace = "http://tempuri.org/")
        java.lang.String param16,
        @WebParam(name = "param17", targetNamespace = "http://tempuri.org/")
        java.lang.String param17,
        @WebParam(name = "param18", targetNamespace = "http://tempuri.org/")
        java.lang.String param18,
        @WebParam(name = "param19", targetNamespace = "http://tempuri.org/")
        java.lang.String param19,
        @WebParam(name = "param20", targetNamespace = "http://tempuri.org/")
        java.lang.String param20
    );

    @WebMethod(operationName = "Dessilenciar_Todos", action = "http://tempuri.org/Dessilenciar_Todos")
    @RequestWrapper(localName = "Dessilenciar_Todos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DessilenciarTodos")
    @ResponseWrapper(localName = "Dessilenciar_TodosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DessilenciarTodosResponse")
    public void dessilenciarTodos(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia
    );

    @WebMethod(operationName = "ScreenRecordStop", action = "http://tempuri.org/ScreenRecordStop")
    @RequestWrapper(localName = "ScreenRecordStop", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenRecordStop")
    @ResponseWrapper(localName = "ScreenRecordStopResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenRecordStopResponse")
    public void screenRecordStop(
        @WebParam(name = "streamName", targetNamespace = "http://tempuri.org/")
        java.lang.String streamName,
        @WebParam(name = "fileName", targetNamespace = "http://tempuri.org/")
        java.lang.String fileName
    );

    @WebMethod(operationName = "CRM_ShowingContact", action = "http://tempuri.org/CRM_ShowingContact")
    @RequestWrapper(localName = "CRM_ShowingContact", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMShowingContact")
    @ResponseWrapper(localName = "CRM_ShowingContactResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMShowingContactResponse")
    public void crmShowingContact(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "BASE", targetNamespace = "http://tempuri.org/")
        int base,
        @WebParam(name = "IDCONTACTO", targetNamespace = "http://tempuri.org/")
        int idcontacto,
        @WebParam(name = "DATA", targetNamespace = "http://tempuri.org/")
        java.lang.String data
    );

    @WebMethod(operationName = "User_HasLicense", action = "http://tempuri.org/User_HasLicense")
    @RequestWrapper(localName = "User_HasLicense", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UserHasLicense")
    @ResponseWrapper(localName = "User_HasLicenseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UserHasLicenseResponse")
    @WebResult(name = "User_HasLicenseResult", targetNamespace = "http://tempuri.org/")
    public boolean userHasLicense(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "API", targetNamespace = "http://tempuri.org/")
        boolean api
    );

    @WebMethod(operationName = "ScreenPacketReceived", action = "http://tempuri.org/ScreenPacketReceived")
    @RequestWrapper(localName = "ScreenPacketReceived", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenPacketReceived")
    @ResponseWrapper(localName = "ScreenPacketReceivedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenPacketReceivedResponse")
    public void screenPacketReceived(
        @WebParam(name = "streamName", targetNamespace = "http://tempuri.org/")
        java.lang.String streamName
    );

    @WebMethod(operationName = "AddScheduleCall", action = "http://tempuri.org/AddScheduleCall")
    @RequestWrapper(localName = "AddScheduleCall", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddScheduleCall")
    @ResponseWrapper(localName = "AddScheduleCallResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddScheduleCallResponse")
    @WebResult(name = "AddScheduleCallResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addScheduleCall(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "BASE", targetNamespace = "http://tempuri.org/")
        int base,
        @WebParam(name = "IDCONTACTO", targetNamespace = "http://tempuri.org/")
        int idcontacto,
        @WebParam(name = "DATA", targetNamespace = "http://tempuri.org/")
        java.lang.String data,
        @WebParam(name = "TELEFONO", targetNamespace = "http://tempuri.org/")
        java.lang.String telefono,
        @WebParam(name = "FECHA_AGENDA", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaAGENDA
    );

    @WebMethod(operationName = "CRM_No_Disponible", action = "http://tempuri.org/CRM_No_Disponible")
    @RequestWrapper(localName = "CRM_No_Disponible", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMNoDisponible")
    @ResponseWrapper(localName = "CRM_No_DisponibleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMNoDisponibleResponse")
    public void crmNoDisponible(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Silenciar_Todos", action = "http://tempuri.org/Silenciar_Todos")
    @RequestWrapper(localName = "Silenciar_Todos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SilenciarTodos")
    @ResponseWrapper(localName = "Silenciar_TodosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SilenciarTodosResponse")
    public void silenciarTodos(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia
    );

    @WebMethod(operationName = "JoinConference", action = "http://tempuri.org/JoinConference")
    @RequestWrapper(localName = "JoinConference", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JoinConference")
    @ResponseWrapper(localName = "JoinConferenceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.JoinConferenceResponse")
    public void joinConference(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "CancelInvitation", action = "http://tempuri.org/CancelInvitation")
    @RequestWrapper(localName = "CancelInvitation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelInvitation")
    @ResponseWrapper(localName = "CancelInvitationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelInvitationResponse")
    public void cancelInvitation(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Tiempo_Administrativo", action = "http://tempuri.org/Tiempo_Administrativo")
    @RequestWrapper(localName = "Tiempo_Administrativo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TiempoAdministrativo")
    @ResponseWrapper(localName = "Tiempo_AdministrativoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TiempoAdministrativoResponse")
    public void tiempoAdministrativo(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "TIEMPO_ADM", targetNamespace = "http://tempuri.org/")
        boolean tiempoADM
    );

    @WebMethod(operationName = "ExecuteTask06", action = "http://tempuri.org/ExecuteTask06")
    @RequestWrapper(localName = "ExecuteTask06", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask06")
    @ResponseWrapper(localName = "ExecuteTask06Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask06Response")
    @WebResult(name = "ExecuteTask06Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask06(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6
    );

    @WebMethod(operationName = "ExecuteTask07", action = "http://tempuri.org/ExecuteTask07")
    @RequestWrapper(localName = "ExecuteTask07", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask07")
    @ResponseWrapper(localName = "ExecuteTask07Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask07Response")
    @WebResult(name = "ExecuteTask07Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask07(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7
    );

    @WebMethod(operationName = "ExecuteTask08", action = "http://tempuri.org/ExecuteTask08")
    @RequestWrapper(localName = "ExecuteTask08", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask08")
    @ResponseWrapper(localName = "ExecuteTask08Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask08Response")
    @WebResult(name = "ExecuteTask08Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask08(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8
    );

    @WebMethod(operationName = "ExecuteTask09", action = "http://tempuri.org/ExecuteTask09")
    @RequestWrapper(localName = "ExecuteTask09", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask09")
    @ResponseWrapper(localName = "ExecuteTask09Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask09Response")
    @WebResult(name = "ExecuteTask09Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask09(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9
    );

    @WebMethod(operationName = "RemoveHostExceptionWeb", action = "http://tempuri.org/RemoveHostExceptionWeb")
    @RequestWrapper(localName = "RemoveHostExceptionWeb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveHostExceptionWeb")
    @ResponseWrapper(localName = "RemoveHostExceptionWebResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveHostExceptionWebResponse")
    public void removeHostExceptionWeb(
        @WebParam(name = "HOST", targetNamespace = "http://tempuri.org/")
        java.lang.String host
    );

    @WebMethod(operationName = "ExecuteTask13", action = "http://tempuri.org/ExecuteTask13")
    @RequestWrapper(localName = "ExecuteTask13", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask13")
    @ResponseWrapper(localName = "ExecuteTask13Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask13Response")
    @WebResult(name = "ExecuteTask13Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask13(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11,
        @WebParam(name = "param12", targetNamespace = "http://tempuri.org/")
        java.lang.String param12,
        @WebParam(name = "param13", targetNamespace = "http://tempuri.org/")
        java.lang.String param13
    );

    @WebMethod(operationName = "ExecuteTask14", action = "http://tempuri.org/ExecuteTask14")
    @RequestWrapper(localName = "ExecuteTask14", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask14")
    @ResponseWrapper(localName = "ExecuteTask14Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask14Response")
    @WebResult(name = "ExecuteTask14Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask14(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11,
        @WebParam(name = "param12", targetNamespace = "http://tempuri.org/")
        java.lang.String param12,
        @WebParam(name = "param13", targetNamespace = "http://tempuri.org/")
        java.lang.String param13,
        @WebParam(name = "param14", targetNamespace = "http://tempuri.org/")
        java.lang.String param14
    );

    @WebMethod(operationName = "ExecuteTask15", action = "http://tempuri.org/ExecuteTask15")
    @RequestWrapper(localName = "ExecuteTask15", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask15")
    @ResponseWrapper(localName = "ExecuteTask15Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask15Response")
    @WebResult(name = "ExecuteTask15Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask15(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11,
        @WebParam(name = "param12", targetNamespace = "http://tempuri.org/")
        java.lang.String param12,
        @WebParam(name = "param13", targetNamespace = "http://tempuri.org/")
        java.lang.String param13,
        @WebParam(name = "param14", targetNamespace = "http://tempuri.org/")
        java.lang.String param14,
        @WebParam(name = "param15", targetNamespace = "http://tempuri.org/")
        java.lang.String param15
    );

    @WebMethod(operationName = "ExecuteTask16", action = "http://tempuri.org/ExecuteTask16")
    @RequestWrapper(localName = "ExecuteTask16", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask16")
    @ResponseWrapper(localName = "ExecuteTask16Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask16Response")
    @WebResult(name = "ExecuteTask16Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask16(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11,
        @WebParam(name = "param12", targetNamespace = "http://tempuri.org/")
        java.lang.String param12,
        @WebParam(name = "param13", targetNamespace = "http://tempuri.org/")
        java.lang.String param13,
        @WebParam(name = "param14", targetNamespace = "http://tempuri.org/")
        java.lang.String param14,
        @WebParam(name = "param15", targetNamespace = "http://tempuri.org/")
        java.lang.String param15,
        @WebParam(name = "param16", targetNamespace = "http://tempuri.org/")
        java.lang.String param16
    );

    @WebMethod(operationName = "AddHostExceptionTel", action = "http://tempuri.org/AddHostExceptionTel")
    @RequestWrapper(localName = "AddHostExceptionTel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddHostExceptionTel")
    @ResponseWrapper(localName = "AddHostExceptionTelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddHostExceptionTelResponse")
    public void addHostExceptionTel(
        @WebParam(name = "HOST", targetNamespace = "http://tempuri.org/")
        java.lang.String host
    );

    @WebMethod(operationName = "ExecuteTask10", action = "http://tempuri.org/ExecuteTask10")
    @RequestWrapper(localName = "ExecuteTask10", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask10")
    @ResponseWrapper(localName = "ExecuteTask10Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask10Response")
    @WebResult(name = "ExecuteTask10Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask10(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10
    );

    @WebMethod(operationName = "ExecuteTask11", action = "http://tempuri.org/ExecuteTask11")
    @RequestWrapper(localName = "ExecuteTask11", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask11")
    @ResponseWrapper(localName = "ExecuteTask11Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask11Response")
    @WebResult(name = "ExecuteTask11Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask11(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11
    );

    @WebMethod(operationName = "Position", action = "http://tempuri.org/Position")
    @RequestWrapper(localName = "Position", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Position")
    @ResponseWrapper(localName = "PositionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PositionResponse")
    @WebResult(name = "PositionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String position(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "ExecuteTask12", action = "http://tempuri.org/ExecuteTask12")
    @RequestWrapper(localName = "ExecuteTask12", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask12")
    @ResponseWrapper(localName = "ExecuteTask12Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask12Response")
    @WebResult(name = "ExecuteTask12Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask12(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5,
        @WebParam(name = "param6", targetNamespace = "http://tempuri.org/")
        java.lang.String param6,
        @WebParam(name = "param7", targetNamespace = "http://tempuri.org/")
        java.lang.String param7,
        @WebParam(name = "param8", targetNamespace = "http://tempuri.org/")
        java.lang.String param8,
        @WebParam(name = "param9", targetNamespace = "http://tempuri.org/")
        java.lang.String param9,
        @WebParam(name = "param10", targetNamespace = "http://tempuri.org/")
        java.lang.String param10,
        @WebParam(name = "param11", targetNamespace = "http://tempuri.org/")
        java.lang.String param11,
        @WebParam(name = "param12", targetNamespace = "http://tempuri.org/")
        java.lang.String param12
    );

    @WebMethod(operationName = "Expulsar_Todos", action = "http://tempuri.org/Expulsar_Todos")
    @RequestWrapper(localName = "Expulsar_Todos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExpulsarTodos")
    @ResponseWrapper(localName = "Expulsar_TodosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExpulsarTodosResponse")
    public void expulsarTodos(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia
    );

    @WebMethod(operationName = "Logout", action = "http://tempuri.org/Logout")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogoutResponse")
    public void logout(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "UnmuteAll", action = "http://tempuri.org/UnmuteAll")
    @RequestWrapper(localName = "UnmuteAll", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnmuteAll")
    @ResponseWrapper(localName = "UnmuteAllResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnmuteAllResponse")
    public void unmuteAll(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia
    );

    @WebMethod(operationName = "SaveRemoteImage", action = "http://tempuri.org/SaveRemoteImage")
    @RequestWrapper(localName = "SaveRemoteImage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveRemoteImage")
    @ResponseWrapper(localName = "SaveRemoteImageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveRemoteImageResponse")
    public void saveRemoteImage(
        @WebParam(name = "imageUrl", targetNamespace = "http://tempuri.org/")
        java.lang.String imageUrl,
        @WebParam(name = "localPath", targetNamespace = "http://tempuri.org/")
        java.lang.String localPath
    );

    @WebMethod(operationName = "StopMonitor", action = "http://tempuri.org/StopMonitor")
    @RequestWrapper(localName = "StopMonitor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StopMonitor")
    @ResponseWrapper(localName = "StopMonitorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StopMonitorResponse")
    public void stopMonitor(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "BlindTransfer", action = "http://tempuri.org/BlindTransfer")
    @RequestWrapper(localName = "BlindTransfer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BlindTransfer")
    @ResponseWrapper(localName = "BlindTransferResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BlindTransferResponse")
    public void blindTransfer(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "EXTENSION", targetNamespace = "http://tempuri.org/")
        java.lang.String extension
    );

    @WebMethod(operationName = "Pause", action = "http://tempuri.org/Pause")
    @RequestWrapper(localName = "Pause", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Pause")
    @ResponseWrapper(localName = "PauseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PauseResponse")
    public void pause(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "SUBTIPO_DESCANSO", targetNamespace = "http://tempuri.org/")
        int subtipoDESCANSO
    );

    @WebMethod(operationName = "Device_Delete", action = "http://tempuri.org/Device_Delete")
    @RequestWrapper(localName = "Device_Delete", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeviceDelete")
    @ResponseWrapper(localName = "Device_DeleteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeviceDeleteResponse")
    public void deviceDelete(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "DEVICE", targetNamespace = "http://tempuri.org/")
        java.lang.String device
    );

    @WebMethod(operationName = "Device_Update", action = "http://tempuri.org/Device_Update")
    @RequestWrapper(localName = "Device_Update", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeviceUpdate")
    @ResponseWrapper(localName = "Device_UpdateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeviceUpdateResponse")
    public void deviceUpdate(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "DEVICE", targetNamespace = "http://tempuri.org/")
        java.lang.String device,
        @WebParam(name = "CLAVE", targetNamespace = "http://tempuri.org/")
        java.lang.String clave,
        @WebParam(name = "FECHA_EXPIRACION", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaEXPIRACION,
        @WebParam(name = "CONFIGURACION", targetNamespace = "http://tempuri.org/")
        java.lang.String configuracion,
        @WebParam(name = "ENABLED", targetNamespace = "http://tempuri.org/")
        boolean enabled,
        @WebParam(name = "CANALES_MAX", targetNamespace = "http://tempuri.org/")
        int canalesMAX,
        @WebParam(name = "TASA_DISCADO_MAXIMA", targetNamespace = "http://tempuri.org/")
        int tasaDISCADOMAXIMA,
        @WebParam(name = "TIPO_ASTERISK", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoASTERISK,
        @WebParam(name = "TIPO_NEOTEL", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoNEOTEL,
        @WebParam(name = "PROVEEDOR", targetNamespace = "http://tempuri.org/")
        java.lang.String proveedor,
        @WebParam(name = "EXTRAER", targetNamespace = "http://tempuri.org/")
        int extraer,
        @WebParam(name = "ANTEPONER", targetNamespace = "http://tempuri.org/")
        java.lang.String anteponer,
        @WebParam(name = "CALLERID_DEFAULT", targetNamespace = "http://tempuri.org/")
        java.lang.String calleridDEFAULT,
        @WebParam(name = "CALLERID_RANGE", targetNamespace = "http://tempuri.org/")
        java.lang.String calleridRANGE,
        @WebParam(name = "DESCRIPCION", targetNamespace = "http://tempuri.org/")
        java.lang.String descripcion
    );

    @WebMethod(operationName = "ScreenPingReceived", action = "http://tempuri.org/ScreenPingReceived")
    @RequestWrapper(localName = "ScreenPingReceived", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenPingReceived")
    @ResponseWrapper(localName = "ScreenPingReceivedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenPingReceivedResponse")
    public void screenPingReceived(
        @WebParam(name = "streamName", targetNamespace = "http://tempuri.org/")
        java.lang.String streamName
    );

    @WebMethod(operationName = "Expulsar_Participante", action = "http://tempuri.org/Expulsar_Participante")
    @RequestWrapper(localName = "Expulsar_Participante", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExpulsarParticipante")
    @ResponseWrapper(localName = "Expulsar_ParticipanteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExpulsarParticipanteResponse")
    public void expulsarParticipante(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia,
        @WebParam(name = "PARTICIPANTE", targetNamespace = "http://tempuri.org/")
        int participante
    );

    @WebMethod(operationName = "CRM_Disponible", action = "http://tempuri.org/CRM_Disponible")
    @RequestWrapper(localName = "CRM_Disponible", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMDisponible")
    @ResponseWrapper(localName = "CRM_DisponibleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMDisponibleResponse")
    public void crmDisponible(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Login_Campaña", action = "http://tempuri.org/Login_Campaña")
    @RequestWrapper(localName = "Login_Campaña", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginCampaña")
    @ResponseWrapper(localName = "Login_CampañaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginCampañaResponse")
    public void loginCampaña(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CAMPAÑA", targetNamespace = "http://tempuri.org/")
        int campaña
    );

    @WebMethod(operationName = "CloseContact", action = "http://tempuri.org/CloseContact")
    @RequestWrapper(localName = "CloseContact", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CloseContact")
    @ResponseWrapper(localName = "CloseContactResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CloseContactResponse")
    public void closeContact(
        @WebParam(name = "BASE", targetNamespace = "http://tempuri.org/")
        int base,
        @WebParam(name = "IDCONTACTO", targetNamespace = "http://tempuri.org/")
        int idcontacto
    );

    @WebMethod(operationName = "AddInternetExceptionWeb", action = "http://tempuri.org/AddInternetExceptionWeb")
    @RequestWrapper(localName = "AddInternetExceptionWeb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddInternetExceptionWeb")
    @ResponseWrapper(localName = "AddInternetExceptionWebResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddInternetExceptionWebResponse")
    public void addInternetExceptionWeb();

    @WebMethod(operationName = "AddHostExceptionWeb", action = "http://tempuri.org/AddHostExceptionWeb")
    @RequestWrapper(localName = "AddHostExceptionWeb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddHostExceptionWeb")
    @ResponseWrapper(localName = "AddHostExceptionWebResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddHostExceptionWebResponse")
    public void addHostExceptionWeb(
        @WebParam(name = "HOST", targetNamespace = "http://tempuri.org/")
        java.lang.String host
    );

    @WebMethod(operationName = "BlindTransferQueue", action = "http://tempuri.org/BlindTransferQueue")
    @RequestWrapper(localName = "BlindTransferQueue", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BlindTransferQueue")
    @ResponseWrapper(localName = "BlindTransferQueueResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BlindTransferQueueResponse")
    public void blindTransferQueue(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "COLA", targetNamespace = "http://tempuri.org/")
        int cola
    );

    @WebMethod(operationName = "AttendedTransferQueue", action = "http://tempuri.org/AttendedTransferQueue")
    @RequestWrapper(localName = "AttendedTransferQueue", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AttendedTransferQueue")
    @ResponseWrapper(localName = "AttendedTransferQueueResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AttendedTransferQueueResponse")
    public void attendedTransferQueue(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "COLA", targetNamespace = "http://tempuri.org/")
        int cola
    );

    @WebMethod(operationName = "ScreenRecordStart", action = "http://tempuri.org/ScreenRecordStart")
    @RequestWrapper(localName = "ScreenRecordStart", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenRecordStart")
    @ResponseWrapper(localName = "ScreenRecordStartResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenRecordStartResponse")
    public void screenRecordStart(
        @WebParam(name = "streamName", targetNamespace = "http://tempuri.org/")
        java.lang.String streamName,
        @WebParam(name = "fileName", targetNamespace = "http://tempuri.org/")
        java.lang.String fileName
    );

    @WebMethod(operationName = "CRM_Available", action = "http://tempuri.org/CRM_Available")
    @RequestWrapper(localName = "CRM_Available", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMAvailable")
    @ResponseWrapper(localName = "CRM_AvailableResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMAvailableResponse")
    public void crmAvailable(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "InviteParticipant", action = "http://tempuri.org/InviteParticipant")
    @RequestWrapper(localName = "InviteParticipant", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InviteParticipant")
    @ResponseWrapper(localName = "InviteParticipantResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InviteParticipantResponse")
    public void inviteParticipant(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "EXTENSION", targetNamespace = "http://tempuri.org/")
        java.lang.String extension
    );

    @WebMethod(operationName = "Posicion", action = "http://tempuri.org/Posicion")
    @RequestWrapper(localName = "Posicion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Posicion")
    @ResponseWrapper(localName = "PosicionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PosicionResponse")
    @WebResult(name = "PosicionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String posicion(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "ReloadBlockedIncoming", action = "http://tempuri.org/ReloadBlockedIncoming")
    @RequestWrapper(localName = "ReloadBlockedIncoming", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReloadBlockedIncoming")
    @ResponseWrapper(localName = "ReloadBlockedIncomingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReloadBlockedIncomingResponse")
    public void reloadBlockedIncoming();

    @WebMethod(operationName = "Logout_Campaña", action = "http://tempuri.org/Logout_Campaña")
    @RequestWrapper(localName = "Logout_Campaña", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogoutCampaña")
    @ResponseWrapper(localName = "Logout_CampañaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogoutCampañaResponse")
    public void logoutCampaña(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Eliminar_Dispositivo", action = "http://tempuri.org/Eliminar_Dispositivo")
    @RequestWrapper(localName = "Eliminar_Dispositivo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarDispositivo")
    @ResponseWrapper(localName = "Eliminar_DispositivoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminarDispositivoResponse")
    public void eliminarDispositivo(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "DEVICE", targetNamespace = "http://tempuri.org/")
        java.lang.String device,
        @WebParam(name = "InternalCall", targetNamespace = "http://tempuri.org/")
        boolean internalCall
    );

    @WebMethod(operationName = "Dial", action = "http://tempuri.org/Dial")
    @RequestWrapper(localName = "Dial", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Dial")
    @ResponseWrapper(localName = "DialResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DialResponse")
    @WebResult(name = "DialResult", targetNamespace = "http://tempuri.org/")
    public boolean dial(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "TELEFONO", targetNamespace = "http://tempuri.org/")
        java.lang.String telefono
    );

    @WebMethod(operationName = "ReloadBlockedOutgoing", action = "http://tempuri.org/ReloadBlockedOutgoing")
    @RequestWrapper(localName = "ReloadBlockedOutgoing", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReloadBlockedOutgoing")
    @ResponseWrapper(localName = "ReloadBlockedOutgoingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReloadBlockedOutgoingResponse")
    public void reloadBlockedOutgoing();

    @WebMethod(operationName = "User_Update", action = "http://tempuri.org/User_Update")
    @RequestWrapper(localName = "User_Update", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UserUpdate")
    @ResponseWrapper(localName = "User_UpdateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UserUpdateResponse")
    public void userUpdate(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CLAVE", targetNamespace = "http://tempuri.org/")
        java.lang.String clave,
        @WebParam(name = "TIPO", targetNamespace = "http://tempuri.org/")
        java.lang.String tipo,
        @WebParam(name = "GRABA_CONVERSACION", targetNamespace = "http://tempuri.org/")
        boolean grabaCONVERSACION,
        @WebParam(name = "GRABA_PANTALLA", targetNamespace = "http://tempuri.org/")
        boolean grabaPANTALLA,
        @WebParam(name = "DETECTA_PALABRAS", targetNamespace = "http://tempuri.org/")
        boolean detectaPALABRAS,
        @WebParam(name = "EMAIL", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(name = "TELEFONO", targetNamespace = "http://tempuri.org/")
        java.lang.String telefono,
        @WebParam(name = "NOMBRE", targetNamespace = "http://tempuri.org/")
        java.lang.String nombre,
        @WebParam(name = "APELLIDO", targetNamespace = "http://tempuri.org/")
        java.lang.String apellido,
        @WebParam(name = "CAMBIA_CLAVE_PROX_LOGIN", targetNamespace = "http://tempuri.org/")
        boolean cambiaCLAVEPROXLOGIN,
        @WebParam(name = "SAL_CALLERID_PRESENTATION", targetNamespace = "http://tempuri.org/")
        int salCALLERIDPRESENTATION,
        @WebParam(name = "SAL_CALLERID", targetNamespace = "http://tempuri.org/")
        java.lang.String salCALLERID,
        @WebParam(name = "SAL_RUTA", targetNamespace = "http://tempuri.org/")
        int salRUTA,
        @WebParam(name = "SAL_PRECIO", targetNamespace = "http://tempuri.org/")
        int salPRECIO,
        @WebParam(name = "ENT_DNIS", targetNamespace = "http://tempuri.org/")
        java.lang.String entDNIS,
        @WebParam(name = "ENT_TIMEOUT", targetNamespace = "http://tempuri.org/")
        int entTIMEOUT,
        @WebParam(name = "ENT_LOCUCION", targetNamespace = "http://tempuri.org/")
        int entLOCUCION,
        @WebParam(name = "FECHA_ALTA", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaALTA,
        @WebParam(name = "DOMICILIO", targetNamespace = "http://tempuri.org/")
        java.lang.String domicilio,
        @WebParam(name = "LOCALIDAD", targetNamespace = "http://tempuri.org/")
        java.lang.String localidad,
        @WebParam(name = "DNI", targetNamespace = "http://tempuri.org/")
        java.lang.String dni,
        @WebParam(name = "IDPERFIL", targetNamespace = "http://tempuri.org/")
        int idperfil,
        @WebParam(name = "VERIFICA_PERMISOS", targetNamespace = "http://tempuri.org/")
        boolean verificaPERMISOS
    );

    @WebMethod(operationName = "AddInternetExceptionTel", action = "http://tempuri.org/AddInternetExceptionTel")
    @RequestWrapper(localName = "AddInternetExceptionTel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddInternetExceptionTel")
    @ResponseWrapper(localName = "AddInternetExceptionTelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddInternetExceptionTelResponse")
    public void addInternetExceptionTel();

    @WebMethod(operationName = "Insertar_Dispositivo", action = "http://tempuri.org/Insertar_Dispositivo")
    @RequestWrapper(localName = "Insertar_Dispositivo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertarDispositivo")
    @ResponseWrapper(localName = "Insertar_DispositivoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertarDispositivoResponse")
    public void insertarDispositivo(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "DEVICE", targetNamespace = "http://tempuri.org/")
        java.lang.String device,
        @WebParam(name = "CLAVE", targetNamespace = "http://tempuri.org/")
        java.lang.String clave,
        @WebParam(name = "FECHA_EXPIRACION", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaEXPIRACION,
        @WebParam(name = "CONFIGURACION", targetNamespace = "http://tempuri.org/")
        java.lang.String configuracion,
        @WebParam(name = "ENABLED", targetNamespace = "http://tempuri.org/")
        boolean enabled,
        @WebParam(name = "CANALES_MAX", targetNamespace = "http://tempuri.org/")
        int canalesMAX,
        @WebParam(name = "TIPO_ASTERISK", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoASTERISK,
        @WebParam(name = "TIPO_NEOTEL", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoNEOTEL,
        @WebParam(name = "PROVEEDOR", targetNamespace = "http://tempuri.org/")
        java.lang.String proveedor,
        @WebParam(name = "DESCRIPCION", targetNamespace = "http://tempuri.org/")
        java.lang.String descripcion,
        @WebParam(name = "InternalCall", targetNamespace = "http://tempuri.org/")
        boolean internalCall
    );

    @WebMethod(operationName = "ScreenStreamClose", action = "http://tempuri.org/ScreenStreamClose")
    @RequestWrapper(localName = "ScreenStreamClose", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenStreamClose")
    @ResponseWrapper(localName = "ScreenStreamCloseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenStreamCloseResponse")
    public void screenStreamClose(
        @WebParam(name = "streamName", targetNamespace = "http://tempuri.org/")
        java.lang.String streamName
    );

    @WebMethod(operationName = "KickParticipant", action = "http://tempuri.org/KickParticipant")
    @RequestWrapper(localName = "KickParticipant", targetNamespace = "http://tempuri.org/", className = "org.tempuri.KickParticipant")
    @ResponseWrapper(localName = "KickParticipantResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.KickParticipantResponse")
    public void kickParticipant(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia,
        @WebParam(name = "PARTICIPANTE", targetNamespace = "http://tempuri.org/")
        int participante
    );

    @WebMethod(operationName = "Unpause", action = "http://tempuri.org/Unpause")
    @RequestWrapper(localName = "Unpause", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Unpause")
    @ResponseWrapper(localName = "UnpauseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnpauseResponse")
    public void unpause(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "CRM_Unavailable", action = "http://tempuri.org/CRM_Unavailable")
    @RequestWrapper(localName = "CRM_Unavailable", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMUnavailable")
    @ResponseWrapper(localName = "CRM_UnavailableResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMUnavailableResponse")
    @WebResult(name = "CRM_UnavailableResult", targetNamespace = "http://tempuri.org/")
    public boolean crmUnavailable(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Discar", action = "http://tempuri.org/Discar")
    @RequestWrapper(localName = "Discar", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Discar")
    @ResponseWrapper(localName = "DiscarResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DiscarResponse")
    public void discar(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "TELEFONO", targetNamespace = "http://tempuri.org/")
        java.lang.String telefono
    );

    @WebMethod(operationName = "Dessilenciar_Participante", action = "http://tempuri.org/Dessilenciar_Participante")
    @RequestWrapper(localName = "Dessilenciar_Participante", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DessilenciarParticipante")
    @ResponseWrapper(localName = "Dessilenciar_ParticipanteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DessilenciarParticipanteResponse")
    public void dessilenciarParticipante(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia,
        @WebParam(name = "PARTICIPANTE", targetNamespace = "http://tempuri.org/")
        int participante
    );

    @WebMethod(operationName = "MuteAll", action = "http://tempuri.org/MuteAll")
    @RequestWrapper(localName = "MuteAll", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MuteAll")
    @ResponseWrapper(localName = "MuteAllResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MuteAllResponse")
    public void muteAll(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia
    );

    @WebMethod(operationName = "User_Insert", action = "http://tempuri.org/User_Insert")
    @RequestWrapper(localName = "User_Insert", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UserInsert")
    @ResponseWrapper(localName = "User_InsertResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UserInsertResponse")
    public void userInsert(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CLAVE", targetNamespace = "http://tempuri.org/")
        java.lang.String clave,
        @WebParam(name = "TIPO", targetNamespace = "http://tempuri.org/")
        java.lang.String tipo,
        @WebParam(name = "GRABA_CONVERSACION", targetNamespace = "http://tempuri.org/")
        boolean grabaCONVERSACION,
        @WebParam(name = "GRABA_PANTALLA", targetNamespace = "http://tempuri.org/")
        boolean grabaPANTALLA,
        @WebParam(name = "DETECTA_PALABRAS", targetNamespace = "http://tempuri.org/")
        boolean detectaPALABRAS,
        @WebParam(name = "EMAIL", targetNamespace = "http://tempuri.org/")
        java.lang.String email,
        @WebParam(name = "TELEFONO", targetNamespace = "http://tempuri.org/")
        java.lang.String telefono,
        @WebParam(name = "NOMBRE", targetNamespace = "http://tempuri.org/")
        java.lang.String nombre,
        @WebParam(name = "APELLIDO", targetNamespace = "http://tempuri.org/")
        java.lang.String apellido,
        @WebParam(name = "CAMBIA_CLAVE_PROX_LOGIN", targetNamespace = "http://tempuri.org/")
        boolean cambiaCLAVEPROXLOGIN,
        @WebParam(name = "SAL_CALLERID_PRESENTATION", targetNamespace = "http://tempuri.org/")
        int salCALLERIDPRESENTATION,
        @WebParam(name = "SAL_CALLERID", targetNamespace = "http://tempuri.org/")
        java.lang.String salCALLERID,
        @WebParam(name = "SAL_RUTA", targetNamespace = "http://tempuri.org/")
        int salRUTA,
        @WebParam(name = "SAL_PRECIO", targetNamespace = "http://tempuri.org/")
        int salPRECIO,
        @WebParam(name = "ENT_DNIS", targetNamespace = "http://tempuri.org/")
        java.lang.String entDNIS,
        @WebParam(name = "ENT_TIMEOUT", targetNamespace = "http://tempuri.org/")
        int entTIMEOUT,
        @WebParam(name = "ENT_LOCUCION", targetNamespace = "http://tempuri.org/")
        int entLOCUCION,
        @WebParam(name = "FECHA_ALTA", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaALTA,
        @WebParam(name = "DOMICILIO", targetNamespace = "http://tempuri.org/")
        java.lang.String domicilio,
        @WebParam(name = "LOCALIDAD", targetNamespace = "http://tempuri.org/")
        java.lang.String localidad,
        @WebParam(name = "DNI", targetNamespace = "http://tempuri.org/")
        java.lang.String dni,
        @WebParam(name = "IDPERFIL", targetNamespace = "http://tempuri.org/")
        int idperfil,
        @WebParam(name = "VERIFICA_PERMISOS", targetNamespace = "http://tempuri.org/")
        java.lang.String verificaPERMISOS
    );

    @WebMethod(operationName = "Detener_Grabacion", action = "http://tempuri.org/Detener_Grabacion")
    @RequestWrapper(localName = "Detener_Grabacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DetenerGrabacion")
    @ResponseWrapper(localName = "Detener_GrabacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DetenerGrabacionResponse")
    public void detenerGrabacion(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Cortar", action = "http://tempuri.org/Cortar")
    @RequestWrapper(localName = "Cortar", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Cortar")
    @ResponseWrapper(localName = "CortarResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CortarResponse")
    public void cortar(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "AttendedTransfer", action = "http://tempuri.org/AttendedTransfer")
    @RequestWrapper(localName = "AttendedTransfer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AttendedTransfer")
    @ResponseWrapper(localName = "AttendedTransferResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AttendedTransferResponse")
    public void attendedTransfer(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "EXTENSION", targetNamespace = "http://tempuri.org/")
        java.lang.String extension
    );

    @WebMethod(operationName = "Login_Campaign2", action = "http://tempuri.org/Login_Campaign2")
    @RequestWrapper(localName = "Login_Campaign2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginCampaign2")
    @ResponseWrapper(localName = "Login_Campaign2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginCampaign2Response")
    public void loginCampaign2(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CAMPANA", targetNamespace = "http://tempuri.org/")
        int campana
    );

    @WebMethod(operationName = "UpdateContact", action = "http://tempuri.org/UpdateContact")
    @RequestWrapper(localName = "UpdateContact", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateContact")
    @ResponseWrapper(localName = "UpdateContactResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateContactResponse")
    public void updateContact(
        @WebParam(name = "CRM", targetNamespace = "http://tempuri.org/")
        int crm,
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "BASE", targetNamespace = "http://tempuri.org/")
        int base,
        @WebParam(name = "IDCONTACTO", targetNamespace = "http://tempuri.org/")
        int idcontacto,
        @WebParam(name = "DATA", targetNamespace = "http://tempuri.org/")
        java.lang.String data,
        @WebParam(name = "SUBCATEGORIA", targetNamespace = "http://tempuri.org/")
        int subcategoria,
        @WebParam(name = "XML_UPDATE", targetNamespace = "http://tempuri.org/")
        java.lang.String xmlUPDATE,
        @WebParam(name = "AGENDA", targetNamespace = "http://tempuri.org/")
        boolean agenda,
        @WebParam(name = "FECHA_AGENDA", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaAGENDA,
        @WebParam(name = "USUARIO_AGENDA", targetNamespace = "http://tempuri.org/")
        java.lang.String usuarioAGENDA,
        @WebParam(name = "TEL_AGENDA", targetNamespace = "http://tempuri.org/")
        java.lang.String telAGENDA
    );

    @WebMethod(operationName = "Device_Insert", action = "http://tempuri.org/Device_Insert")
    @RequestWrapper(localName = "Device_Insert", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeviceInsert")
    @ResponseWrapper(localName = "Device_InsertResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeviceInsertResponse")
    public void deviceInsert(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "DEVICE", targetNamespace = "http://tempuri.org/")
        java.lang.String device,
        @WebParam(name = "CLAVE", targetNamespace = "http://tempuri.org/")
        java.lang.String clave,
        @WebParam(name = "FECHA_EXPIRACION", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fechaEXPIRACION,
        @WebParam(name = "CONFIGURACION", targetNamespace = "http://tempuri.org/")
        java.lang.String configuracion,
        @WebParam(name = "ENABLED", targetNamespace = "http://tempuri.org/")
        boolean enabled,
        @WebParam(name = "CANALES_MAX", targetNamespace = "http://tempuri.org/")
        int canalesMAX,
        @WebParam(name = "TASA_DISCADO_MAXIMA", targetNamespace = "http://tempuri.org/")
        int tasaDISCADOMAXIMA,
        @WebParam(name = "TIPO_ASTERISK", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoASTERISK,
        @WebParam(name = "TIPO_NEOTEL", targetNamespace = "http://tempuri.org/")
        java.lang.String tipoNEOTEL,
        @WebParam(name = "PROVEEDOR", targetNamespace = "http://tempuri.org/")
        java.lang.String proveedor,
        @WebParam(name = "EXTRAER", targetNamespace = "http://tempuri.org/")
        int extraer,
        @WebParam(name = "ANTEPONER", targetNamespace = "http://tempuri.org/")
        java.lang.String anteponer,
        @WebParam(name = "CALLERID_DEFAULT", targetNamespace = "http://tempuri.org/")
        java.lang.String calleridDEFAULT,
        @WebParam(name = "CALLERID_RANGE", targetNamespace = "http://tempuri.org/")
        java.lang.String calleridRANGE,
        @WebParam(name = "DESCRIPCION", targetNamespace = "http://tempuri.org/")
        java.lang.String descripcion
    );

    @WebMethod(operationName = "ExecuteTask02", action = "http://tempuri.org/ExecuteTask02")
    @RequestWrapper(localName = "ExecuteTask02", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask02")
    @ResponseWrapper(localName = "ExecuteTask02Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask02Response")
    @WebResult(name = "ExecuteTask02Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask02(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2
    );

    @WebMethod(operationName = "MuteParticipant", action = "http://tempuri.org/MuteParticipant")
    @RequestWrapper(localName = "MuteParticipant", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MuteParticipant")
    @ResponseWrapper(localName = "MuteParticipantResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MuteParticipantResponse")
    public void muteParticipant(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia,
        @WebParam(name = "PARTICIPANTE", targetNamespace = "http://tempuri.org/")
        int participante
    );

    @WebMethod(operationName = "ExecuteTask03", action = "http://tempuri.org/ExecuteTask03")
    @RequestWrapper(localName = "ExecuteTask03", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask03")
    @ResponseWrapper(localName = "ExecuteTask03Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask03Response")
    @WebResult(name = "ExecuteTask03Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask03(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3
    );

    @WebMethod(operationName = "ExecuteTask04", action = "http://tempuri.org/ExecuteTask04")
    @RequestWrapper(localName = "ExecuteTask04", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask04")
    @ResponseWrapper(localName = "ExecuteTask04Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask04Response")
    @WebResult(name = "ExecuteTask04Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask04(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4
    );

    @WebMethod(operationName = "StartMonitor", action = "http://tempuri.org/StartMonitor")
    @RequestWrapper(localName = "StartMonitor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartMonitor")
    @ResponseWrapper(localName = "StartMonitorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartMonitorResponse")
    public void startMonitor(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "ExecuteTask05", action = "http://tempuri.org/ExecuteTask05")
    @RequestWrapper(localName = "ExecuteTask05", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask05")
    @ResponseWrapper(localName = "ExecuteTask05Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask05Response")
    @WebResult(name = "ExecuteTask05Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask05(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1,
        @WebParam(name = "param2", targetNamespace = "http://tempuri.org/")
        java.lang.String param2,
        @WebParam(name = "param3", targetNamespace = "http://tempuri.org/")
        java.lang.String param3,
        @WebParam(name = "param4", targetNamespace = "http://tempuri.org/")
        java.lang.String param4,
        @WebParam(name = "param5", targetNamespace = "http://tempuri.org/")
        java.lang.String param5
    );

    @WebMethod(operationName = "Silenciar_Participante", action = "http://tempuri.org/Silenciar_Participante")
    @RequestWrapper(localName = "Silenciar_Participante", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SilenciarParticipante")
    @ResponseWrapper(localName = "Silenciar_ParticipanteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SilenciarParticipanteResponse")
    public void silenciarParticipante(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia,
        @WebParam(name = "PARTICIPANTE", targetNamespace = "http://tempuri.org/")
        int participante
    );

    @WebMethod(operationName = "ExecuteTask00", action = "http://tempuri.org/ExecuteTask00")
    @RequestWrapper(localName = "ExecuteTask00", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask00")
    @ResponseWrapper(localName = "ExecuteTask00Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask00Response")
    @WebResult(name = "ExecuteTask00Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask00(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask
    );

    @WebMethod(operationName = "ExecuteTask01", action = "http://tempuri.org/ExecuteTask01")
    @RequestWrapper(localName = "ExecuteTask01", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask01")
    @ResponseWrapper(localName = "ExecuteTask01Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteTask01Response")
    @WebResult(name = "ExecuteTask01Result", targetNamespace = "http://tempuri.org/")
    public java.lang.String executeTask01(
        @WebParam(name = "idTask", targetNamespace = "http://tempuri.org/")
        int idTask,
        @WebParam(name = "param1", targetNamespace = "http://tempuri.org/")
        java.lang.String param1
    );

    @WebMethod(operationName = "Hangup", action = "http://tempuri.org/Hangup")
    @RequestWrapper(localName = "Hangup", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Hangup")
    @ResponseWrapper(localName = "HangupResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HangupResponse")
    public void hangup(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "RemoveInternetExceptionTel", action = "http://tempuri.org/RemoveInternetExceptionTel")
    @RequestWrapper(localName = "RemoveInternetExceptionTel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveInternetExceptionTel")
    @ResponseWrapper(localName = "RemoveInternetExceptionTelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveInternetExceptionTelResponse")
    public void removeInternetExceptionTel();

    @WebMethod(operationName = "CRM_Mostrando_Contacto_CRM_Interno", action = "http://tempuri.org/CRM_Mostrando_Contacto_CRM_Interno")
    @RequestWrapper(localName = "CRM_Mostrando_Contacto_CRM_Interno", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMMostrandoContactoCRMInterno")
    @ResponseWrapper(localName = "CRM_Mostrando_Contacto_CRM_InternoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CRMMostrandoContactoCRMInternoResponse")
    @WebResult(name = "CRM_Mostrando_Contacto_CRM_InternoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String crmMostrandoContactoCRMInterno(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CRM", targetNamespace = "http://tempuri.org/")
        int crm,
        @WebParam(name = "BASE", targetNamespace = "http://tempuri.org/")
        int base,
        @WebParam(name = "IDCONTACTO", targetNamespace = "http://tempuri.org/")
        int idcontacto
    );

    @WebMethod(operationName = "User_Delete", action = "http://tempuri.org/User_Delete")
    @RequestWrapper(localName = "User_Delete", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UserDelete")
    @ResponseWrapper(localName = "User_DeleteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UserDeleteResponse")
    public void userDelete(
        @WebParam(name = "CLIENTE", targetNamespace = "http://tempuri.org/")
        java.lang.String cliente,
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "UnmuteParticipant", action = "http://tempuri.org/UnmuteParticipant")
    @RequestWrapper(localName = "UnmuteParticipant", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnmuteParticipant")
    @ResponseWrapper(localName = "UnmuteParticipantResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UnmuteParticipantResponse")
    public void unmuteParticipant(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "CONFERENCIA", targetNamespace = "http://tempuri.org/")
        int conferencia,
        @WebParam(name = "PARTICIPANTE", targetNamespace = "http://tempuri.org/")
        int participante
    );

    @WebMethod(operationName = "Descanso", action = "http://tempuri.org/Descanso")
    @RequestWrapper(localName = "Descanso", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Descanso")
    @ResponseWrapper(localName = "DescansoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DescansoResponse")
    public void descanso(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "DESCANSO", targetNamespace = "http://tempuri.org/")
        boolean descanso
    );

    @WebMethod(operationName = "SendDTMF", action = "http://tempuri.org/SendDTMF")
    @RequestWrapper(localName = "SendDTMF", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendDTMF")
    @ResponseWrapper(localName = "SendDTMFResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendDTMFResponse")
    public void sendDTMF(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario,
        @WebParam(name = "DIGITOS", targetNamespace = "http://tempuri.org/")
        java.lang.String digitos
    );

    @WebMethod(operationName = "Logout_Campaign", action = "http://tempuri.org/Logout_Campaign")
    @RequestWrapper(localName = "Logout_Campaign", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogoutCampaign")
    @ResponseWrapper(localName = "Logout_CampaignResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogoutCampaignResponse")
    public void logoutCampaign(
        @WebParam(name = "USUARIO", targetNamespace = "http://tempuri.org/")
        java.lang.String usuario
    );

    @WebMethod(operationName = "RemoveHostExceptionTel", action = "http://tempuri.org/RemoveHostExceptionTel")
    @RequestWrapper(localName = "RemoveHostExceptionTel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveHostExceptionTel")
    @ResponseWrapper(localName = "RemoveHostExceptionTelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveHostExceptionTelResponse")
    public void removeHostExceptionTel(
        @WebParam(name = "HOST", targetNamespace = "http://tempuri.org/")
        java.lang.String host
    );

    @WebMethod(operationName = "ScreenStreamStart", action = "http://tempuri.org/ScreenStreamStart")
    @RequestWrapper(localName = "ScreenStreamStart", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenStreamStart")
    @ResponseWrapper(localName = "ScreenStreamStartResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ScreenStreamStartResponse")
    public void screenStreamStart(
        @WebParam(name = "streamName", targetNamespace = "http://tempuri.org/")
        java.lang.String streamName
    );
}
