package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2017-12-29T17:08:11.082-03:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebServiceHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebServiceHttpGet {

    @WebMethod(operationName = "RemoveInternetExceptionWeb")
    public void removeInternetExceptionWeb();

    @WebMethod(operationName = "CRM_Mostrando_Contacto")
    public void crmMostrandoContacto(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "IDCONTACTO", name = "IDCONTACTO", targetNamespace = "")
        java.lang.String idcontacto,
        @WebParam(partName = "DATA", name = "DATA", targetNamespace = "")
        java.lang.String data
    );

    @WebMethod(operationName = "Iniciar_Grabacion")
    public void iniciarGrabacion(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Modificar_Dispositivo")
    public void modificarDispositivo(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "DEVICE", name = "DEVICE", targetNamespace = "")
        java.lang.String device,
        @WebParam(partName = "CLAVE", name = "CLAVE", targetNamespace = "")
        java.lang.String clave,
        @WebParam(partName = "FECHA_EXPIRACION", name = "FECHA_EXPIRACION", targetNamespace = "")
        java.lang.String fechaEXPIRACION,
        @WebParam(partName = "CONFIGURACION", name = "CONFIGURACION", targetNamespace = "")
        java.lang.String configuracion,
        @WebParam(partName = "ENABLED", name = "ENABLED", targetNamespace = "")
        java.lang.String enabled,
        @WebParam(partName = "CANALES_MAX", name = "CANALES_MAX", targetNamespace = "")
        java.lang.String canalesMAX,
        @WebParam(partName = "TIPO_ASTERISK", name = "TIPO_ASTERISK", targetNamespace = "")
        java.lang.String tipoASTERISK,
        @WebParam(partName = "TIPO_NEOTEL", name = "TIPO_NEOTEL", targetNamespace = "")
        java.lang.String tipoNEOTEL,
        @WebParam(partName = "PROVEEDOR", name = "PROVEEDOR", targetNamespace = "")
        java.lang.String proveedor,
        @WebParam(partName = "DESCRIPCION", name = "DESCRIPCION", targetNamespace = "")
        java.lang.String descripcion,
        @WebParam(partName = "InternalCall", name = "InternalCall", targetNamespace = "")
        java.lang.String internalCall
    );

    @WebMethod(operationName = "KickAll")
    public void kickAll(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia
    );

    @WebMethod(operationName = "ExecuteTask17")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask17(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11,
        @WebParam(partName = "param12", name = "param12", targetNamespace = "")
        java.lang.String param12,
        @WebParam(partName = "param13", name = "param13", targetNamespace = "")
        java.lang.String param13,
        @WebParam(partName = "param14", name = "param14", targetNamespace = "")
        java.lang.String param14,
        @WebParam(partName = "param15", name = "param15", targetNamespace = "")
        java.lang.String param15,
        @WebParam(partName = "param16", name = "param16", targetNamespace = "")
        java.lang.String param16,
        @WebParam(partName = "param17", name = "param17", targetNamespace = "")
        java.lang.String param17
    );

    @WebMethod(operationName = "ExecuteTask18")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask18(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11,
        @WebParam(partName = "param12", name = "param12", targetNamespace = "")
        java.lang.String param12,
        @WebParam(partName = "param13", name = "param13", targetNamespace = "")
        java.lang.String param13,
        @WebParam(partName = "param14", name = "param14", targetNamespace = "")
        java.lang.String param14,
        @WebParam(partName = "param15", name = "param15", targetNamespace = "")
        java.lang.String param15,
        @WebParam(partName = "param16", name = "param16", targetNamespace = "")
        java.lang.String param16,
        @WebParam(partName = "param17", name = "param17", targetNamespace = "")
        java.lang.String param17,
        @WebParam(partName = "param18", name = "param18", targetNamespace = "")
        java.lang.String param18
    );

    @WebMethod(operationName = "ExecuteTask19")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask19(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11,
        @WebParam(partName = "param12", name = "param12", targetNamespace = "")
        java.lang.String param12,
        @WebParam(partName = "param13", name = "param13", targetNamespace = "")
        java.lang.String param13,
        @WebParam(partName = "param14", name = "param14", targetNamespace = "")
        java.lang.String param14,
        @WebParam(partName = "param15", name = "param15", targetNamespace = "")
        java.lang.String param15,
        @WebParam(partName = "param16", name = "param16", targetNamespace = "")
        java.lang.String param16,
        @WebParam(partName = "param17", name = "param17", targetNamespace = "")
        java.lang.String param17,
        @WebParam(partName = "param18", name = "param18", targetNamespace = "")
        java.lang.String param18,
        @WebParam(partName = "param19", name = "param19", targetNamespace = "")
        java.lang.String param19
    );

    @WebMethod(operationName = "BlindTransferCampaign")
    public void blindTransferCampaign(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CAMPAÑA", name = "CAMPAÑA", targetNamespace = "")
        java.lang.String campaña
    );

    @WebMethod(operationName = "Login_Campaign")
    public void loginCampaign(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CAMPAÑA", name = "CAMPAÑA", targetNamespace = "")
        java.lang.String campaña
    );

    @WebMethod(operationName = "ExecuteTask20")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask20(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11,
        @WebParam(partName = "param12", name = "param12", targetNamespace = "")
        java.lang.String param12,
        @WebParam(partName = "param13", name = "param13", targetNamespace = "")
        java.lang.String param13,
        @WebParam(partName = "param14", name = "param14", targetNamespace = "")
        java.lang.String param14,
        @WebParam(partName = "param15", name = "param15", targetNamespace = "")
        java.lang.String param15,
        @WebParam(partName = "param16", name = "param16", targetNamespace = "")
        java.lang.String param16,
        @WebParam(partName = "param17", name = "param17", targetNamespace = "")
        java.lang.String param17,
        @WebParam(partName = "param18", name = "param18", targetNamespace = "")
        java.lang.String param18,
        @WebParam(partName = "param19", name = "param19", targetNamespace = "")
        java.lang.String param19,
        @WebParam(partName = "param20", name = "param20", targetNamespace = "")
        java.lang.String param20
    );

    @WebMethod(operationName = "Dessilenciar_Todos")
    public void dessilenciarTodos(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia
    );

    @WebMethod(operationName = "ScreenRecordStop")
    public void screenRecordStop(
        @WebParam(partName = "streamName", name = "streamName", targetNamespace = "")
        java.lang.String streamName,
        @WebParam(partName = "fileName", name = "fileName", targetNamespace = "")
        java.lang.String fileName
    );

    @WebMethod(operationName = "CRM_ShowingContact")
    public void crmShowingContact(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "BASE", name = "BASE", targetNamespace = "")
        java.lang.String base,
        @WebParam(partName = "IDCONTACTO", name = "IDCONTACTO", targetNamespace = "")
        java.lang.String idcontacto,
        @WebParam(partName = "DATA", name = "DATA", targetNamespace = "")
        java.lang.String data
    );

    @WebMethod(operationName = "User_HasLicense")
    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    public boolean userHasLicense(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "API", name = "API", targetNamespace = "")
        java.lang.String api
    );

    @WebMethod(operationName = "ScreenPacketReceived")
    public void screenPacketReceived(
        @WebParam(partName = "streamName", name = "streamName", targetNamespace = "")
        java.lang.String streamName
    );

    @WebMethod(operationName = "AddScheduleCall")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String addScheduleCall(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "BASE", name = "BASE", targetNamespace = "")
        java.lang.String base,
        @WebParam(partName = "IDCONTACTO", name = "IDCONTACTO", targetNamespace = "")
        java.lang.String idcontacto,
        @WebParam(partName = "DATA", name = "DATA", targetNamespace = "")
        java.lang.String data,
        @WebParam(partName = "TELEFONO", name = "TELEFONO", targetNamespace = "")
        java.lang.String telefono,
        @WebParam(partName = "FECHA_AGENDA", name = "FECHA_AGENDA", targetNamespace = "")
        java.lang.String fechaAGENDA
    );

    @WebMethod(operationName = "CRM_No_Disponible")
    public void crmNoDisponible(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Silenciar_Todos")
    public void silenciarTodos(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia
    );

    @WebMethod(operationName = "JoinConference")
    public void joinConference(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "CancelInvitation")
    public void cancelInvitation(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Tiempo_Administrativo")
    public void tiempoAdministrativo(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "TIEMPO_ADM", name = "TIEMPO_ADM", targetNamespace = "")
        java.lang.String tiempoADM
    );

    @WebMethod(operationName = "ExecuteTask06")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask06(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6
    );

    @WebMethod(operationName = "ExecuteTask07")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask07(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7
    );

    @WebMethod(operationName = "ExecuteTask08")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask08(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8
    );

    @WebMethod(operationName = "ExecuteTask09")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask09(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9
    );

    @WebMethod(operationName = "RemoveHostExceptionWeb")
    public void removeHostExceptionWeb(
        @WebParam(partName = "HOST", name = "HOST", targetNamespace = "")
        java.lang.String host
    );

    @WebMethod(operationName = "ExecuteTask13")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask13(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11,
        @WebParam(partName = "param12", name = "param12", targetNamespace = "")
        java.lang.String param12,
        @WebParam(partName = "param13", name = "param13", targetNamespace = "")
        java.lang.String param13
    );

    @WebMethod(operationName = "ExecuteTask14")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask14(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11,
        @WebParam(partName = "param12", name = "param12", targetNamespace = "")
        java.lang.String param12,
        @WebParam(partName = "param13", name = "param13", targetNamespace = "")
        java.lang.String param13,
        @WebParam(partName = "param14", name = "param14", targetNamespace = "")
        java.lang.String param14
    );

    @WebMethod(operationName = "ExecuteTask15")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask15(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11,
        @WebParam(partName = "param12", name = "param12", targetNamespace = "")
        java.lang.String param12,
        @WebParam(partName = "param13", name = "param13", targetNamespace = "")
        java.lang.String param13,
        @WebParam(partName = "param14", name = "param14", targetNamespace = "")
        java.lang.String param14,
        @WebParam(partName = "param15", name = "param15", targetNamespace = "")
        java.lang.String param15
    );

    @WebMethod(operationName = "ExecuteTask16")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask16(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11,
        @WebParam(partName = "param12", name = "param12", targetNamespace = "")
        java.lang.String param12,
        @WebParam(partName = "param13", name = "param13", targetNamespace = "")
        java.lang.String param13,
        @WebParam(partName = "param14", name = "param14", targetNamespace = "")
        java.lang.String param14,
        @WebParam(partName = "param15", name = "param15", targetNamespace = "")
        java.lang.String param15,
        @WebParam(partName = "param16", name = "param16", targetNamespace = "")
        java.lang.String param16
    );

    @WebMethod(operationName = "AddHostExceptionTel")
    public void addHostExceptionTel(
        @WebParam(partName = "HOST", name = "HOST", targetNamespace = "")
        java.lang.String host
    );

    @WebMethod(operationName = "ExecuteTask10")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask10(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10
    );

    @WebMethod(operationName = "ExecuteTask11")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask11(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11
    );

    @WebMethod(operationName = "Position")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String position(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "ExecuteTask12")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask12(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5,
        @WebParam(partName = "param6", name = "param6", targetNamespace = "")
        java.lang.String param6,
        @WebParam(partName = "param7", name = "param7", targetNamespace = "")
        java.lang.String param7,
        @WebParam(partName = "param8", name = "param8", targetNamespace = "")
        java.lang.String param8,
        @WebParam(partName = "param9", name = "param9", targetNamespace = "")
        java.lang.String param9,
        @WebParam(partName = "param10", name = "param10", targetNamespace = "")
        java.lang.String param10,
        @WebParam(partName = "param11", name = "param11", targetNamespace = "")
        java.lang.String param11,
        @WebParam(partName = "param12", name = "param12", targetNamespace = "")
        java.lang.String param12
    );

    @WebMethod(operationName = "Expulsar_Todos")
    public void expulsarTodos(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia
    );

    @WebMethod(operationName = "Logout")
    public void logout(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "UnmuteAll")
    public void unmuteAll(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia
    );

    @WebMethod(operationName = "SaveRemoteImage")
    public void saveRemoteImage(
        @WebParam(partName = "imageUrl", name = "imageUrl", targetNamespace = "")
        java.lang.String imageUrl,
        @WebParam(partName = "localPath", name = "localPath", targetNamespace = "")
        java.lang.String localPath
    );

    @WebMethod(operationName = "StopMonitor")
    public void stopMonitor(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "BlindTransfer")
    public void blindTransfer(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "EXTENSION", name = "EXTENSION", targetNamespace = "")
        java.lang.String extension
    );

    @WebMethod(operationName = "Pause")
    public void pause(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "SUBTIPO_DESCANSO", name = "SUBTIPO_DESCANSO", targetNamespace = "")
        java.lang.String subtipoDESCANSO
    );

    @WebMethod(operationName = "Device_Delete")
    public void deviceDelete(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "DEVICE", name = "DEVICE", targetNamespace = "")
        java.lang.String device
    );

    @WebMethod(operationName = "Device_Update")
    public void deviceUpdate(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "DEVICE", name = "DEVICE", targetNamespace = "")
        java.lang.String device,
        @WebParam(partName = "CLAVE", name = "CLAVE", targetNamespace = "")
        java.lang.String clave,
        @WebParam(partName = "FECHA_EXPIRACION", name = "FECHA_EXPIRACION", targetNamespace = "")
        java.lang.String fechaEXPIRACION,
        @WebParam(partName = "CONFIGURACION", name = "CONFIGURACION", targetNamespace = "")
        java.lang.String configuracion,
        @WebParam(partName = "ENABLED", name = "ENABLED", targetNamespace = "")
        java.lang.String enabled,
        @WebParam(partName = "CANALES_MAX", name = "CANALES_MAX", targetNamespace = "")
        java.lang.String canalesMAX,
        @WebParam(partName = "TASA_DISCADO_MAXIMA", name = "TASA_DISCADO_MAXIMA", targetNamespace = "")
        java.lang.String tasaDISCADOMAXIMA,
        @WebParam(partName = "TIPO_ASTERISK", name = "TIPO_ASTERISK", targetNamespace = "")
        java.lang.String tipoASTERISK,
        @WebParam(partName = "TIPO_NEOTEL", name = "TIPO_NEOTEL", targetNamespace = "")
        java.lang.String tipoNEOTEL,
        @WebParam(partName = "PROVEEDOR", name = "PROVEEDOR", targetNamespace = "")
        java.lang.String proveedor,
        @WebParam(partName = "EXTRAER", name = "EXTRAER", targetNamespace = "")
        java.lang.String extraer,
        @WebParam(partName = "ANTEPONER", name = "ANTEPONER", targetNamespace = "")
        java.lang.String anteponer,
        @WebParam(partName = "CALLERID_DEFAULT", name = "CALLERID_DEFAULT", targetNamespace = "")
        java.lang.String calleridDEFAULT,
        @WebParam(partName = "CALLERID_RANGE", name = "CALLERID_RANGE", targetNamespace = "")
        java.lang.String calleridRANGE,
        @WebParam(partName = "DESCRIPCION", name = "DESCRIPCION", targetNamespace = "")
        java.lang.String descripcion
    );

    @WebMethod(operationName = "ScreenPingReceived")
    public void screenPingReceived(
        @WebParam(partName = "streamName", name = "streamName", targetNamespace = "")
        java.lang.String streamName
    );

    @WebMethod(operationName = "Expulsar_Participante")
    public void expulsarParticipante(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia,
        @WebParam(partName = "PARTICIPANTE", name = "PARTICIPANTE", targetNamespace = "")
        java.lang.String participante
    );

    @WebMethod(operationName = "CRM_Disponible")
    public void crmDisponible(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Login_Campaña")
    public void loginCampaña(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CAMPAÑA", name = "CAMPAÑA", targetNamespace = "")
        java.lang.String campaña
    );

    @WebMethod(operationName = "CloseContact")
    public void closeContact(
        @WebParam(partName = "BASE", name = "BASE", targetNamespace = "")
        java.lang.String base,
        @WebParam(partName = "IDCONTACTO", name = "IDCONTACTO", targetNamespace = "")
        java.lang.String idcontacto
    );

    @WebMethod(operationName = "AddInternetExceptionWeb")
    public void addInternetExceptionWeb();

    @WebMethod(operationName = "AddHostExceptionWeb")
    public void addHostExceptionWeb(
        @WebParam(partName = "HOST", name = "HOST", targetNamespace = "")
        java.lang.String host
    );

    @WebMethod(operationName = "BlindTransferQueue")
    public void blindTransferQueue(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "COLA", name = "COLA", targetNamespace = "")
        java.lang.String cola
    );

    @WebMethod(operationName = "AttendedTransferQueue")
    public void attendedTransferQueue(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "COLA", name = "COLA", targetNamespace = "")
        java.lang.String cola
    );

    @WebMethod(operationName = "ScreenRecordStart")
    public void screenRecordStart(
        @WebParam(partName = "streamName", name = "streamName", targetNamespace = "")
        java.lang.String streamName,
        @WebParam(partName = "fileName", name = "fileName", targetNamespace = "")
        java.lang.String fileName
    );

    @WebMethod(operationName = "CRM_Available")
    public void crmAvailable(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "InviteParticipant")
    public void inviteParticipant(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "EXTENSION", name = "EXTENSION", targetNamespace = "")
        java.lang.String extension
    );

    @WebMethod(operationName = "Posicion")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String posicion(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "ReloadBlockedIncoming")
    public void reloadBlockedIncoming();

    @WebMethod(operationName = "Logout_Campaña")
    public void logoutCampaña(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Eliminar_Dispositivo")
    public void eliminarDispositivo(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "DEVICE", name = "DEVICE", targetNamespace = "")
        java.lang.String device,
        @WebParam(partName = "InternalCall", name = "InternalCall", targetNamespace = "")
        java.lang.String internalCall
    );

    @WebMethod(operationName = "Dial")
    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    public boolean dial(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "TELEFONO", name = "TELEFONO", targetNamespace = "")
        java.lang.String telefono
    );

    @WebMethod(operationName = "ReloadBlockedOutgoing")
    public void reloadBlockedOutgoing();

    @WebMethod(operationName = "User_Update")
    public void userUpdate(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CLAVE", name = "CLAVE", targetNamespace = "")
        java.lang.String clave,
        @WebParam(partName = "TIPO", name = "TIPO", targetNamespace = "")
        java.lang.String tipo,
        @WebParam(partName = "GRABA_CONVERSACION", name = "GRABA_CONVERSACION", targetNamespace = "")
        java.lang.String grabaCONVERSACION,
        @WebParam(partName = "GRABA_PANTALLA", name = "GRABA_PANTALLA", targetNamespace = "")
        java.lang.String grabaPANTALLA,
        @WebParam(partName = "DETECTA_PALABRAS", name = "DETECTA_PALABRAS", targetNamespace = "")
        java.lang.String detectaPALABRAS,
        @WebParam(partName = "EMAIL", name = "EMAIL", targetNamespace = "")
        java.lang.String email,
        @WebParam(partName = "TELEFONO", name = "TELEFONO", targetNamespace = "")
        java.lang.String telefono,
        @WebParam(partName = "NOMBRE", name = "NOMBRE", targetNamespace = "")
        java.lang.String nombre,
        @WebParam(partName = "APELLIDO", name = "APELLIDO", targetNamespace = "")
        java.lang.String apellido,
        @WebParam(partName = "CAMBIA_CLAVE_PROX_LOGIN", name = "CAMBIA_CLAVE_PROX_LOGIN", targetNamespace = "")
        java.lang.String cambiaCLAVEPROXLOGIN,
        @WebParam(partName = "SAL_CALLERID_PRESENTATION", name = "SAL_CALLERID_PRESENTATION", targetNamespace = "")
        java.lang.String salCALLERIDPRESENTATION,
        @WebParam(partName = "SAL_CALLERID", name = "SAL_CALLERID", targetNamespace = "")
        java.lang.String salCALLERID,
        @WebParam(partName = "SAL_RUTA", name = "SAL_RUTA", targetNamespace = "")
        java.lang.String salRUTA,
        @WebParam(partName = "SAL_PRECIO", name = "SAL_PRECIO", targetNamespace = "")
        java.lang.String salPRECIO,
        @WebParam(partName = "ENT_DNIS", name = "ENT_DNIS", targetNamespace = "")
        java.lang.String entDNIS,
        @WebParam(partName = "ENT_TIMEOUT", name = "ENT_TIMEOUT", targetNamespace = "")
        java.lang.String entTIMEOUT,
        @WebParam(partName = "ENT_LOCUCION", name = "ENT_LOCUCION", targetNamespace = "")
        java.lang.String entLOCUCION,
        @WebParam(partName = "FECHA_ALTA", name = "FECHA_ALTA", targetNamespace = "")
        java.lang.String fechaALTA,
        @WebParam(partName = "DOMICILIO", name = "DOMICILIO", targetNamespace = "")
        java.lang.String domicilio,
        @WebParam(partName = "LOCALIDAD", name = "LOCALIDAD", targetNamespace = "")
        java.lang.String localidad,
        @WebParam(partName = "DNI", name = "DNI", targetNamespace = "")
        java.lang.String dni,
        @WebParam(partName = "IDPERFIL", name = "IDPERFIL", targetNamespace = "")
        java.lang.String idperfil,
        @WebParam(partName = "VERIFICA_PERMISOS", name = "VERIFICA_PERMISOS", targetNamespace = "")
        java.lang.String verificaPERMISOS
    );

    @WebMethod(operationName = "AddInternetExceptionTel")
    public void addInternetExceptionTel();

    @WebMethod(operationName = "Insertar_Dispositivo")
    public void insertarDispositivo(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "DEVICE", name = "DEVICE", targetNamespace = "")
        java.lang.String device,
        @WebParam(partName = "CLAVE", name = "CLAVE", targetNamespace = "")
        java.lang.String clave,
        @WebParam(partName = "FECHA_EXPIRACION", name = "FECHA_EXPIRACION", targetNamespace = "")
        java.lang.String fechaEXPIRACION,
        @WebParam(partName = "CONFIGURACION", name = "CONFIGURACION", targetNamespace = "")
        java.lang.String configuracion,
        @WebParam(partName = "ENABLED", name = "ENABLED", targetNamespace = "")
        java.lang.String enabled,
        @WebParam(partName = "CANALES_MAX", name = "CANALES_MAX", targetNamespace = "")
        java.lang.String canalesMAX,
        @WebParam(partName = "TIPO_ASTERISK", name = "TIPO_ASTERISK", targetNamespace = "")
        java.lang.String tipoASTERISK,
        @WebParam(partName = "TIPO_NEOTEL", name = "TIPO_NEOTEL", targetNamespace = "")
        java.lang.String tipoNEOTEL,
        @WebParam(partName = "PROVEEDOR", name = "PROVEEDOR", targetNamespace = "")
        java.lang.String proveedor,
        @WebParam(partName = "DESCRIPCION", name = "DESCRIPCION", targetNamespace = "")
        java.lang.String descripcion,
        @WebParam(partName = "InternalCall", name = "InternalCall", targetNamespace = "")
        java.lang.String internalCall
    );

    @WebMethod(operationName = "ScreenStreamClose")
    public void screenStreamClose(
        @WebParam(partName = "streamName", name = "streamName", targetNamespace = "")
        java.lang.String streamName
    );

    @WebMethod(operationName = "KickParticipant")
    public void kickParticipant(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia,
        @WebParam(partName = "PARTICIPANTE", name = "PARTICIPANTE", targetNamespace = "")
        java.lang.String participante
    );

    @WebMethod(operationName = "Unpause")
    public void unpause(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "CRM_Unavailable")
    @WebResult(name = "boolean", targetNamespace = "http://tempuri.org/", partName = "Body")
    public boolean crmUnavailable(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Discar")
    public void discar(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "TELEFONO", name = "TELEFONO", targetNamespace = "")
        java.lang.String telefono
    );

    @WebMethod(operationName = "Dessilenciar_Participante")
    public void dessilenciarParticipante(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia,
        @WebParam(partName = "PARTICIPANTE", name = "PARTICIPANTE", targetNamespace = "")
        java.lang.String participante
    );

    @WebMethod(operationName = "MuteAll")
    public void muteAll(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia
    );

    @WebMethod(operationName = "User_Insert")
    public void userInsert(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CLAVE", name = "CLAVE", targetNamespace = "")
        java.lang.String clave,
        @WebParam(partName = "TIPO", name = "TIPO", targetNamespace = "")
        java.lang.String tipo,
        @WebParam(partName = "GRABA_CONVERSACION", name = "GRABA_CONVERSACION", targetNamespace = "")
        java.lang.String grabaCONVERSACION,
        @WebParam(partName = "GRABA_PANTALLA", name = "GRABA_PANTALLA", targetNamespace = "")
        java.lang.String grabaPANTALLA,
        @WebParam(partName = "DETECTA_PALABRAS", name = "DETECTA_PALABRAS", targetNamespace = "")
        java.lang.String detectaPALABRAS,
        @WebParam(partName = "EMAIL", name = "EMAIL", targetNamespace = "")
        java.lang.String email,
        @WebParam(partName = "TELEFONO", name = "TELEFONO", targetNamespace = "")
        java.lang.String telefono,
        @WebParam(partName = "NOMBRE", name = "NOMBRE", targetNamespace = "")
        java.lang.String nombre,
        @WebParam(partName = "APELLIDO", name = "APELLIDO", targetNamespace = "")
        java.lang.String apellido,
        @WebParam(partName = "CAMBIA_CLAVE_PROX_LOGIN", name = "CAMBIA_CLAVE_PROX_LOGIN", targetNamespace = "")
        java.lang.String cambiaCLAVEPROXLOGIN,
        @WebParam(partName = "SAL_CALLERID_PRESENTATION", name = "SAL_CALLERID_PRESENTATION", targetNamespace = "")
        java.lang.String salCALLERIDPRESENTATION,
        @WebParam(partName = "SAL_CALLERID", name = "SAL_CALLERID", targetNamespace = "")
        java.lang.String salCALLERID,
        @WebParam(partName = "SAL_RUTA", name = "SAL_RUTA", targetNamespace = "")
        java.lang.String salRUTA,
        @WebParam(partName = "SAL_PRECIO", name = "SAL_PRECIO", targetNamespace = "")
        java.lang.String salPRECIO,
        @WebParam(partName = "ENT_DNIS", name = "ENT_DNIS", targetNamespace = "")
        java.lang.String entDNIS,
        @WebParam(partName = "ENT_TIMEOUT", name = "ENT_TIMEOUT", targetNamespace = "")
        java.lang.String entTIMEOUT,
        @WebParam(partName = "ENT_LOCUCION", name = "ENT_LOCUCION", targetNamespace = "")
        java.lang.String entLOCUCION,
        @WebParam(partName = "FECHA_ALTA", name = "FECHA_ALTA", targetNamespace = "")
        java.lang.String fechaALTA,
        @WebParam(partName = "DOMICILIO", name = "DOMICILIO", targetNamespace = "")
        java.lang.String domicilio,
        @WebParam(partName = "LOCALIDAD", name = "LOCALIDAD", targetNamespace = "")
        java.lang.String localidad,
        @WebParam(partName = "DNI", name = "DNI", targetNamespace = "")
        java.lang.String dni,
        @WebParam(partName = "IDPERFIL", name = "IDPERFIL", targetNamespace = "")
        java.lang.String idperfil,
        @WebParam(partName = "VERIFICA_PERMISOS", name = "VERIFICA_PERMISOS", targetNamespace = "")
        java.lang.String verificaPERMISOS
    );

    @WebMethod(operationName = "Detener_Grabacion")
    public void detenerGrabacion(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "Cortar")
    public void cortar(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "AttendedTransfer")
    public void attendedTransfer(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "EXTENSION", name = "EXTENSION", targetNamespace = "")
        java.lang.String extension
    );

    @WebMethod(operationName = "Login_Campaign2")
    public void loginCampaign2(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CAMPANA", name = "CAMPANA", targetNamespace = "")
        java.lang.String campana
    );

    @WebMethod(operationName = "UpdateContact")
    public void updateContact(
        @WebParam(partName = "CRM", name = "CRM", targetNamespace = "")
        java.lang.String crm,
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "BASE", name = "BASE", targetNamespace = "")
        java.lang.String base,
        @WebParam(partName = "IDCONTACTO", name = "IDCONTACTO", targetNamespace = "")
        java.lang.String idcontacto,
        @WebParam(partName = "DATA", name = "DATA", targetNamespace = "")
        java.lang.String data,
        @WebParam(partName = "SUBCATEGORIA", name = "SUBCATEGORIA", targetNamespace = "")
        java.lang.String subcategoria,
        @WebParam(partName = "XML_UPDATE", name = "XML_UPDATE", targetNamespace = "")
        java.lang.String xmlUPDATE,
        @WebParam(partName = "AGENDA", name = "AGENDA", targetNamespace = "")
        java.lang.String agenda,
        @WebParam(partName = "FECHA_AGENDA", name = "FECHA_AGENDA", targetNamespace = "")
        java.lang.String fechaAGENDA,
        @WebParam(partName = "USUARIO_AGENDA", name = "USUARIO_AGENDA", targetNamespace = "")
        java.lang.String usuarioAGENDA,
        @WebParam(partName = "TEL_AGENDA", name = "TEL_AGENDA", targetNamespace = "")
        java.lang.String telAGENDA
    );

    @WebMethod(operationName = "Device_Insert")
    public void deviceInsert(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "DEVICE", name = "DEVICE", targetNamespace = "")
        java.lang.String device,
        @WebParam(partName = "CLAVE", name = "CLAVE", targetNamespace = "")
        java.lang.String clave,
        @WebParam(partName = "FECHA_EXPIRACION", name = "FECHA_EXPIRACION", targetNamespace = "")
        java.lang.String fechaEXPIRACION,
        @WebParam(partName = "CONFIGURACION", name = "CONFIGURACION", targetNamespace = "")
        java.lang.String configuracion,
        @WebParam(partName = "ENABLED", name = "ENABLED", targetNamespace = "")
        java.lang.String enabled,
        @WebParam(partName = "CANALES_MAX", name = "CANALES_MAX", targetNamespace = "")
        java.lang.String canalesMAX,
        @WebParam(partName = "TASA_DISCADO_MAXIMA", name = "TASA_DISCADO_MAXIMA", targetNamespace = "")
        java.lang.String tasaDISCADOMAXIMA,
        @WebParam(partName = "TIPO_ASTERISK", name = "TIPO_ASTERISK", targetNamespace = "")
        java.lang.String tipoASTERISK,
        @WebParam(partName = "TIPO_NEOTEL", name = "TIPO_NEOTEL", targetNamespace = "")
        java.lang.String tipoNEOTEL,
        @WebParam(partName = "PROVEEDOR", name = "PROVEEDOR", targetNamespace = "")
        java.lang.String proveedor,
        @WebParam(partName = "EXTRAER", name = "EXTRAER", targetNamespace = "")
        java.lang.String extraer,
        @WebParam(partName = "ANTEPONER", name = "ANTEPONER", targetNamespace = "")
        java.lang.String anteponer,
        @WebParam(partName = "CALLERID_DEFAULT", name = "CALLERID_DEFAULT", targetNamespace = "")
        java.lang.String calleridDEFAULT,
        @WebParam(partName = "CALLERID_RANGE", name = "CALLERID_RANGE", targetNamespace = "")
        java.lang.String calleridRANGE,
        @WebParam(partName = "DESCRIPCION", name = "DESCRIPCION", targetNamespace = "")
        java.lang.String descripcion
    );

    @WebMethod(operationName = "ExecuteTask02")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask02(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2
    );

    @WebMethod(operationName = "MuteParticipant")
    public void muteParticipant(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia,
        @WebParam(partName = "PARTICIPANTE", name = "PARTICIPANTE", targetNamespace = "")
        java.lang.String participante
    );

    @WebMethod(operationName = "ExecuteTask03")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask03(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3
    );

    @WebMethod(operationName = "ExecuteTask04")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask04(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4
    );

    @WebMethod(operationName = "StartMonitor")
    public void startMonitor(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "ExecuteTask05")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask05(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1,
        @WebParam(partName = "param2", name = "param2", targetNamespace = "")
        java.lang.String param2,
        @WebParam(partName = "param3", name = "param3", targetNamespace = "")
        java.lang.String param3,
        @WebParam(partName = "param4", name = "param4", targetNamespace = "")
        java.lang.String param4,
        @WebParam(partName = "param5", name = "param5", targetNamespace = "")
        java.lang.String param5
    );

    @WebMethod(operationName = "Silenciar_Participante")
    public void silenciarParticipante(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia,
        @WebParam(partName = "PARTICIPANTE", name = "PARTICIPANTE", targetNamespace = "")
        java.lang.String participante
    );

    @WebMethod(operationName = "ExecuteTask00")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask00(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask
    );

    @WebMethod(operationName = "ExecuteTask01")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String executeTask01(
        @WebParam(partName = "idTask", name = "idTask", targetNamespace = "")
        java.lang.String idTask,
        @WebParam(partName = "param1", name = "param1", targetNamespace = "")
        java.lang.String param1
    );

    @WebMethod(operationName = "Hangup")
    public void hangup(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "RemoveInternetExceptionTel")
    public void removeInternetExceptionTel();

    @WebMethod(operationName = "CRM_Mostrando_Contacto_CRM_Interno")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String crmMostrandoContactoCRMInterno(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CRM", name = "CRM", targetNamespace = "")
        java.lang.String crm,
        @WebParam(partName = "BASE", name = "BASE", targetNamespace = "")
        java.lang.String base,
        @WebParam(partName = "IDCONTACTO", name = "IDCONTACTO", targetNamespace = "")
        java.lang.String idcontacto
    );

    @WebMethod(operationName = "User_Delete")
    public void userDelete(
        @WebParam(partName = "CLIENTE", name = "CLIENTE", targetNamespace = "")
        java.lang.String cliente,
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "UnmuteParticipant")
    public void unmuteParticipant(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "CONFERENCIA", name = "CONFERENCIA", targetNamespace = "")
        java.lang.String conferencia,
        @WebParam(partName = "PARTICIPANTE", name = "PARTICIPANTE", targetNamespace = "")
        java.lang.String participante
    );

    @WebMethod(operationName = "Descanso")
    public void descanso(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "DESCANSO", name = "DESCANSO", targetNamespace = "")
        java.lang.String descanso
    );

    @WebMethod(operationName = "SendDTMF")
    public void sendDTMF(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(partName = "DIGITOS", name = "DIGITOS", targetNamespace = "")
        java.lang.String digitos
    );

    @WebMethod(operationName = "Logout_Campaign")
    public void logoutCampaign(
        @WebParam(partName = "USUARIO", name = "USUARIO", targetNamespace = "")
        java.lang.String usuario
    );

    @WebMethod(operationName = "RemoveHostExceptionTel")
    public void removeHostExceptionTel(
        @WebParam(partName = "HOST", name = "HOST", targetNamespace = "")
        java.lang.String host
    );

    @WebMethod(operationName = "ScreenStreamStart")
    public void screenStreamStart(
        @WebParam(partName = "streamName", name = "streamName", targetNamespace = "")
        java.lang.String streamName
    );
}
